/**
 * Cloudinary Asset Public IDs
 * Auto-generated by migrate-to-cloudinary.ts
 * 
 * Usage:
 *   import { CLOUDINARY_ASSETS } from './cloudinary-assets';
 *   
 *   // In component:
 *   <CldImage src={CLOUDINARY_ASSETS.gallery.vehicle1Before} ... />
 */

export const CLOUDINARY_CLOUD_NAME = 'dgpicy4uv';

export const CLOUDINARY_ASSETS = {
  gallery: {
    vehicle1Before: 'quickspit/gallery/vehicle1-before',
    vehicle1After: 'quickspit/gallery/vehicle1-after',
    vehicle2Before: 'quickspit/gallery/vehicle2-before',
    vehicle2After: 'quickspit/gallery/vehicle2-after',
    example1: 'quickspit/gallery/ex_1',
    example2: 'quickspit/gallery/ex_2',
    example3: 'quickspit/gallery/ex_3',
    example4: 'quickspit/gallery/ex_4',
    example5: 'quickspit/gallery/ex_5',
    example6: 'quickspit/gallery/ex_6',
    example7: 'quickspit/gallery/ex_7',
    example8: 'quickspit/gallery/ex_8',
    example9: 'quickspit/gallery/ex_9',
    owner: 'quickspit/gallery/owner',
  },
  static: {
    herofallback: 'quickspit/static/hero-fallback',
    owner: 'quickspit/static/owner',
  },
} as const;

// Helper to generate Cloudinary URLs
export function cloudinaryUrl(publicId: string, options?: {
  width?: number;
  height?: number;
  crop?: string;
  quality?: string;
  format?: string;
}): string {
  const { width, height, crop = 'fill', quality = 'auto', format = 'auto' } = options || {};
  
  const transformations: string[] = [];
  if (width) transformations.push(`w_${width}`);
  if (height) transformations.push(`h_${height}`);
  if (crop) transformations.push(`c_${crop}`);
  if (quality) transformations.push(`q_${quality}`);
  if (format) transformations.push(`f_${format}`);
  
  const transformString = transformations.length > 0 ? transformations.join(',') + '/' : '';
  
  return `https://res.cloudinary.com/${CLOUDINARY_CLOUD_NAME}/image/upload/${transformString}${publicId}`;
}
